name: CI Check for PRs

on:
  pull_request:
    branches: [main]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm" # Cache NPM dependencies

      - name: Install Dependencies Across Workspaces
        run: npm ci

      - name: Setup Prisma in FE
        run: npm run prisma-setup

      - name: Build All Projects
        run: npm run build

      - name: Test All Projects
        run: npm run test
