name: CI Check for PRs

# This workflow runs on PRs to 'main'
on:
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Node.js
      - name: Setup Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm" # Cache NPM dependencies

      # 3. Install dependencies
      - name: Install Dependencies
        run: npm ci # Using 'npm ci' is recommended for CI as it uses the package-lock.json

      # 4. Run linters
      # - not set up yet

      # 5. Compile smart contracts
      - name: Compile Smart Contracts
        run: npx hardhat compile

      # 6. Run tests
      - name: Run Tests
        run: npx hardhat test
